name: glance
description: An APM library for detecting UI jank in Flutter for mobile (Android/iOS).
version: 0.4.0
homepage: https://github.com/littleGnAl/glance
environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: '>=3.7.0'
dependencies:
  flutter:
    sdk: flutter
  ffi: '>=1.1.2'
  meta: '>=1.9.1'
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  fake_async: ^1.3.1
flutter:
  plugin:
    platforms:
      android:
        package: com.littlegnal.glance
        pluginClass: GlancePlugin
      ios:
        pluginClass: GlancePlugin
