# This action will create a change logs via release-it and open a pull request, 
# after the PR is merged, the action release.yml will be trigger.
name: Prepare release

on:
  workflow_dispatch:
    inputs:
      release_branch:
        description: The branch to be released
        type: string
        required: true
        default: 'main'

      version:
        description: 'The version to be released'
        required: true
        type: string

jobs:
  prepare_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.release_branch }}
          fetch-depth: 0
      - name: Install release-it
        run: |
          npm install -g release-it
          npm install -g release-it/bumper
          npm install -g release-it/conventional-changelog
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: Check releasing
        run: | # Ensure we can run release-it successfully after merged
          release-it ${{ inputs.version }} \
            --no-git.commit \
            --'git.commitMessage="Release ${version}"' \
            --git.tag \
            --'git.tagName="${version}"' \
            --'git.tagAnnotation="Release ${version}"' \
            --git.push \
            --github.release \
            --no-github.web \
            --ci
            --dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run release-it
        id: release_it_step
        run: |
          # Eliminate the warning: WARNING The recommended bump is "xxx", but is overridden with "xxx".
          # Adding `ignoreRecommendedBump` to the `.release-it.json` file is not work for me. Use `grep` to filter it.
          CHANGELOG=$(release-it ${{ inputs.version }} --changelog  2>&1 | grep -Pv 'WARNING The recommended bump is.*')
          echo "The CHANGELOG: ${CHANGELOG}"
          # https://github.com/orgs/community/discussions/26288#discussioncomment-3876281
          delimiter="EOF"
          echo "changelog<<${delimiter}" >> "${GITHUB_OUTPUT}"
          echo "${CHANGELOG}" >> "${GITHUB_OUTPUT}"
          echo "${delimiter}" >> "${GITHUB_OUTPUT}"

          release-it ${{ inputs.version }} \
            --git.commit \
            --'git.commitMessage="Release ${version}"' \
            --no-git.tag \
            --'git.tagAnnotation="Release ${version}"' \
            --no-git.push \
            --no-github.release \
            --no-github.web \
            --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get current version of pubspec.yaml
        id: pubspec
        run: |
          PUBSPEC_VERSION=$(grep 'version: ' pubspec.yaml | sed -e 's,.*: \(.*\),\1,')
          echo "pubspec version: ${PUBSPEC_VERSION}"
          echo "{version}=${PUBSPEC_VERSION}" >> $GITHUB_OUTPUT
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Release ${{ inputs.version }}"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: prepare-release-${{ inputs.version }}
          base: main
          delete-branch: true
          title: "Release ${{ inputs.version }}"
          body: |
            ## Changelog

            ${{ steps.release_it_step.outputs.changelog }}

            *After this pull request is merged, the `release.yml` will be trigger. This pull request is opened by bot*
          labels: |
            ci:skip
            ci:prepare_release
          reviewers: |
            littleGnAl
