name: Publish to Pub.dev 🚀

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+' # '0.2.0'
      
  workflow_dispatch:
    inputs:
      release_branch:
        description: The branch to be released
        type: string
        required: true
        default: 'main'

jobs:
  publishing: # See https://dart.dev/tools/pub/automated-publishing#configuring-a-github-action-workflow-for-publishing-to-pub-dev
    runs-on: ubuntu-latest
    permissions:
        id-token: write # Required for authentication using OIDC
    steps:
      - name: Checkout for workflow_dispatch
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.release_branch }}
          fetch-depth: 0
      - name: Checkout for push tags
        if: ${{ github.event_name == 'push' }}
        uses: actions/checkout@v4

      # Sets the GitHub-signed OIDC token
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Publish
        run: dart pub publish --force