name: Publish to Pub.dev 🚀

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+' # '0.2.0'

jobs:
  publishing: # See https://dart.dev/tools/pub/automated-publishing#configuring-a-github-action-workflow-for-publishing-to-pub-dev
    runs-on: ubuntu-latest
    permissions:
        id-token: write # Required for authentication using OIDC
    steps:
      - name: Checkout for push tags
        uses: actions/checkout@v4

      # Sets the GitHub-signed OIDC token
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Publish
        run: dart pub publish --force