name: Release to Github release/pub.dev and tag 🚀

on:
  pull_request:
    types:
      - closed

jobs:
  release_if_merged:
    if: ${{ github.event.pull_request.merged == true && 
            github.event.pull_request.base.ref == 'main' && 
            contains(github.event.pull_request.labels.*.name, 'ci:prepare_release') }}
    outputs:
      release_version: ${{steps.release.outputs.version}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          # Use the PAT to checkout the codes, see https://github.com/cycjimmy/semantic-release-action/issues/128
          token: ${{ secrets.PAT }}
      - name: Install release-it
        run: |
          npm install -g release-it
          npm install -g release-it/bumper
          npm install -g release-it/conventional-changelog
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: Release
        id: release
        run: |
          PUBSPEC_VERSION=$(grep 'version: ' pubspec.yaml | sed -e 's,.*: \(.*\),\1,')
          echo "pubspec version: ${PUBSPEC_VERSION}"

          release-it ${PUBSPEC_VERSION} \
            --no-git.commit \
            --'git.commitMessage="Release ${version}"' \
            --git.tag \
            --'git.tagName="${version}"' \
            --'git.tagAnnotation="Release ${version}"' \
            --git.push \
            --github.release \
            --no-github.web \
            --ci
          echo "::set-output name=version::${PUBSPEC_VERSION}"
        env:
          # Use PAT to run the release-it, or the pubdev-publishing.yml will not be triggered
          # see https://github.com/orgs/community/discussions/27194#discussioncomment-7038913
          GITHUB_TOKEN: ${{ secrets.PAT }}
