name: Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:

jobs:
#   flutter_codestyle_check:
#     name: Flutter codestyle/analyze check
#     if: ${{ !contains(github.event.pull_request.labels.*.name, 'ci:skip') }}
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: subosito/flutter-action@v2
#         with:
#           channel: 'stable'
#       - name: Check Dart Format
#         run: bash ci/dart_pub_publish_check.sh
#       - uses: axel-op/dart-package-analyzer@v3
#         id: analysis
#         with:
#           githubToken: ${{ secrets.GITHUB_TOKEN }}
#       - name: Check scores
#         env:
#           TOTAL: ${{ steps.analysis.outputs.total }}
#           TOTAL_MAX: ${{ steps.analysis.outputs.total_max }}
#         run: |
#           if (( $TOTAL_MAX - $TOTAL > 10 ))
#           then
#             echo Pub Score too low.
#             exit 1
#           fi

  flutter_ut:
    name: Flutter unit test
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'ci:skip') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter test

  integration_test_android:
    name: Run Flutter Android Integration Tests
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'ci:skip') }}
    strategy:
      matrix:
        # version: ["3.0.0", "3.x"]
        version: ["3.x"]
    runs-on: macos-12 #ubuntu-latest # We did want to run the Android test on ubuntu, but after install the llvm, there's no enough memory to create a AVD
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.version }}
    #   - name: Install LLVM and Clang
    #     uses: KyleMayes/install-llvm-action@v1
    #     with:
    #       version: "15.0.6"
    #   - name: Enable KVM
    #     run: |
    #       echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
    #       sudo udevadm control --reload-rules
    #       sudo udevadm trigger --name-match=kvm
      - name: export llvm
        run: |
            # https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md
            BREW_PREFIX=$(brew --prefix llvm@15)
            export PATH="${BREW_PREFIX}/bin:$PATH"
            which llvm-symbolizer
          
    #   - name: run flutter android integration tests
    #     uses: reactivecircus/android-emulator-runner@v2
    #     with:
    #       api-level: 31
    #       arch: x86_64
    #       profile: pixel_5
    #       ram-size: 2048M
    #       heap-size: 4096M
    #       disk-size: 8192M
    #       script: |
    #         # https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md
    #         export PATH="${$(brew --prefix llvm@15)}/bin:$PATH"
    #         bash scripts/glance_integration_test.sh